# Javascript Node CircleCI 2.0 configuration file
#
# See https://circleci.com/docs/2.0/language-javascript/ for more details.
#
version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    # Specify the version you desire here.
    - image: circleci/node:12

    # Specify service dependencies here if necessary.
    # CircleCI maintains a library of pre-built images,
    # documented in https://circleci.com/docs/2.0/circleci-images/

commands:
  install:
    steps:
      - checkout

      # CircleCI breaks master branch which affects format check below. See
      # https://discuss.circleci.com/t/checkout-script-adds-commits-to-master-from-circle-branch/14194
      - run:
          name: restore master
          command: |
            git checkout master
            git reset --hard origin/master
            git checkout -

      # Download cached dependencies.
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            # Fallback to using the latest cache if no exact match is found.
            - v2-dependencies-

      - run: yarn

      # Upload dependencies cache.
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

jobs:
  test:
    <<: *defaults
    steps:
      - install
      - run: yarn test
      - run: yarn lint-css
      - run: yarn lint-ts
      - run: yarn format-check

  test_full:
    <<: *defaults
    steps:
      - install
      - run: yarn test
      - run: yarn lint-css
      - run: yarn lint-ts
      - run: yarn format-check

workflows:
  version: 2

  commit:
    jobs:
      - test

  daily:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - test_full
