- 'http://localhost:8000**'
- 'http://millionsongdataset.com/pages/getting-dataset/#subset'
- 'https://marketplace.visualstudio.com/items?itemName=stkb.rewrap'
- 'https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml'
- 'https://remote.dvc.org/get-started'
- 'https://sweedom.us10.list-manage.com/subscribe/post?u=a08bf93caae4063c4e6a351f6&amp;id=24c0ecc49a'
- 'https://www.meetup.com/San-Francisco-Machine-Learning-Meetup/events/264846847/'
- 'https://www.reddit.com/r/MachineLearning/comments/bx0apm/d_how_do_you_manage_your_machine_learning/'
- 'https://www.amazon.com/DevOps-Handbook-World-Class-Reliability-Organizations-ebook/dp/B01M9ASFQ3'
- '**linkedin.com/in/**'
- 'link'
- '/img/<filename>.gif'
- '/uploads/images/2020-02-10/image.png'
- 'https://portal.aws.amazon.com/gp/aws/developer/registration/index.html'
- 'https://github.com/iterative/dvc/releases/download/'
- 'https://www.kaggle.com/kurianbenoy/introduction-to-data-version-control-dvc'
- 'https://timheuer.com/blog/skipping-ci-github-actions-workflows/'
