name: Link Check All
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    name: Link Check All
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Link Check
        uses: 'iterative/link-check.action@master'
        with:
          configFile: 'config/link-check/config.yml'
          output: consoleLog
