name: Merge Scheduler
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: 0 6 * * *
# testing fork pr
jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    if: github.repository == 'iterative/dvc.org'
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: squash
          #  Time zone to use. Default is UTC.
          time_zone: 'America/Los_Angeles'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
